### ISSUE TITLE
Defaults?

### ISSUE THREAD

**Issue by mhulse** [mastastealth/sass-flex-mixin#5]
Love this code! Thanks for sharing!

Quick question, but have you thought about setting default values for the mixins? For example:

``` css
// Flexbox "Flex" (shorthand)
// Values: <flex-grow> <flex-shrink> || <flex-basis>
// Default: 0 1 auto

@mixin flex($fg: 0, $fs: 1, $fb: auto) {
    -webkit-box-flex: $fg;
    -webkit-flex: $fg $fs $fb;
    -moz-flex: $fg $fs $fb;
    -ms-flex: $fg $fs $fb;
    flex: $fg $fs $fb;
}
```

By having the defaults defined for the mixin args, I was able to call like so:

```
.demoFlex{
    @include flex(1);
    background:#A9D1FE;
}
```

Whereas without the defaults, I get:

> Syntax error: Mixin flex is missing argument $fs.

I'd be more than happy to do a PR if you think your code could benefit from default values. :+1:
